<?php
/**
 * PaymentIntentsApi
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevDraftAISDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use DevDraftAISDK\ApiException;
use DevDraftAISDK\Configuration;
use DevDraftAISDK\HeaderSelector;
use DevDraftAISDK\ObjectSerializer;

/**
 * PaymentIntentsApi Class Doc Comment
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentIntentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntent
     *
     * Create a bank payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateBankPaymentIntentDto $body Bank payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \DevDraftAISDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function paymentIntentControllerCreateBankPaymentIntent($body, $idempotency_key)
    {
        $this->paymentIntentControllerCreateBankPaymentIntentWithHttpInfo($body, $idempotency_key);
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentWithHttpInfo
     *
     * Create a bank payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateBankPaymentIntentDto $body Bank payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \DevDraftAISDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentIntentControllerCreateBankPaymentIntentWithHttpInfo($body, $idempotency_key)
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateBankPaymentIntentRequest($body, $idempotency_key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentAsync
     *
     * Create a bank payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateBankPaymentIntentDto $body Bank payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateBankPaymentIntentAsync($body, $idempotency_key)
    {
        return $this->paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo($body, $idempotency_key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo
     *
     * Create a bank payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateBankPaymentIntentDto $body Bank payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo($body, $idempotency_key)
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateBankPaymentIntentRequest($body, $idempotency_key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentIntentControllerCreateBankPaymentIntent'
     *
     * @param  \DevDraftAISDK\Model\CreateBankPaymentIntentDto $body Bank payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function paymentIntentControllerCreateBankPaymentIntentRequest($body, $idempotency_key)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling paymentIntentControllerCreateBankPaymentIntent'
            );
        }
        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling paymentIntentControllerCreateBankPaymentIntent'
            );
        }

        $resourcePath = '/api/v0/payment-intents/bank';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($idempotency_key !== null) {
            $headerParams['idempotency-key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntent
     *
     * Create a stable payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateStablePaymentIntentDto $body Stable payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \DevDraftAISDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function paymentIntentControllerCreateStablePaymentIntent($body, $idempotency_key)
    {
        $this->paymentIntentControllerCreateStablePaymentIntentWithHttpInfo($body, $idempotency_key);
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentWithHttpInfo
     *
     * Create a stable payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateStablePaymentIntentDto $body Stable payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \DevDraftAISDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentIntentControllerCreateStablePaymentIntentWithHttpInfo($body, $idempotency_key)
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateStablePaymentIntentRequest($body, $idempotency_key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentAsync
     *
     * Create a stable payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateStablePaymentIntentDto $body Stable payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateStablePaymentIntentAsync($body, $idempotency_key)
    {
        return $this->paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo($body, $idempotency_key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo
     *
     * Create a stable payment intent
     *
     * @param  \DevDraftAISDK\Model\CreateStablePaymentIntentDto $body Stable payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo($body, $idempotency_key)
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateStablePaymentIntentRequest($body, $idempotency_key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentIntentControllerCreateStablePaymentIntent'
     *
     * @param  \DevDraftAISDK\Model\CreateStablePaymentIntentDto $body Stable payment intent creation data (required)
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function paymentIntentControllerCreateStablePaymentIntentRequest($body, $idempotency_key)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling paymentIntentControllerCreateStablePaymentIntent'
            );
        }
        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling paymentIntentControllerCreateStablePaymentIntent'
            );
        }

        $resourcePath = '/api/v0/payment-intents/stablecoin';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($idempotency_key !== null) {
            $headerParams['idempotency-key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
