<?php
/**
 * AllBalancesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevDraftAISDK\Model;

use \ArrayAccess;
use \DevDraftAISDK\ObjectSerializer;

/**
 * AllBalancesResponse Class Doc Comment
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AllBalancesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AllBalancesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'usdc' => 'AllOfAllBalancesResponseUsdc',
        'eurc' => 'AllOfAllBalancesResponseEurc',
        'total_usd_value' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'usdc' => null,
        'eurc' => null,
        'total_usd_value' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'usdc' => 'usdc',
        'eurc' => 'eurc',
        'total_usd_value' => 'total_usd_value'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'usdc' => 'setUsdc',
        'eurc' => 'setEurc',
        'total_usd_value' => 'setTotalUsdValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'usdc' => 'getUsdc',
        'eurc' => 'getEurc',
        'total_usd_value' => 'getTotalUsdValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['usdc'] = isset($data['usdc']) ? $data['usdc'] : null;
        $this->container['eurc'] = isset($data['eurc']) ? $data['eurc'] : null;
        $this->container['total_usd_value'] = isset($data['total_usd_value']) ? $data['total_usd_value'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['usdc'] === null) {
            $invalidProperties[] = "'usdc' can't be null";
        }
        if ($this->container['eurc'] === null) {
            $invalidProperties[] = "'eurc' can't be null";
        }
        if ($this->container['total_usd_value'] === null) {
            $invalidProperties[] = "'total_usd_value' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets usdc
     *
     * @return AllOfAllBalancesResponseUsdc
     */
    public function getUsdc()
    {
        return $this->container['usdc'];
    }

    /**
     * Sets usdc
     *
     * @param AllOfAllBalancesResponseUsdc $usdc USDC balance aggregation
     *
     * @return $this
     */
    public function setUsdc($usdc)
    {
        $this->container['usdc'] = $usdc;

        return $this;
    }

    /**
     * Gets eurc
     *
     * @return AllOfAllBalancesResponseEurc
     */
    public function getEurc()
    {
        return $this->container['eurc'];
    }

    /**
     * Sets eurc
     *
     * @param AllOfAllBalancesResponseEurc $eurc EURC balance aggregation
     *
     * @return $this
     */
    public function setEurc($eurc)
    {
        $this->container['eurc'] = $eurc;

        return $this;
    }

    /**
     * Gets total_usd_value
     *
     * @return string
     */
    public function getTotalUsdValue()
    {
        return $this->container['total_usd_value'];
    }

    /**
     * Sets total_usd_value
     *
     * @param string $total_usd_value Total value in USD equivalent
     *
     * @return $this
     */
    public function setTotalUsdValue($total_usd_value)
    {
        $this->container['total_usd_value'] = $total_usd_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
