<?php
/**
 * BridgePaymentRail
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevDraftAISDK\Model;
use \DevDraftAISDK\ObjectSerializer;

/**
 * BridgePaymentRail Class Doc Comment
 *
 * @category Class
 * @description The blockchain network where the source currency resides. Determines gas fees and transaction speed.
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BridgePaymentRail
{
    /**
     * Possible values of this enum
     */
    const ETHEREUM = 'ethereum';
    const SOLANA = 'solana';
    const POLYGON = 'polygon';
    const AVALANCHE_C_CHAIN = 'avalanche_c_chain';
    const BASE = 'base';
    const ARBITRUM = 'arbitrum';
    const OPTIMISM = 'optimism';
    const STELLAR = 'stellar';
    const TRON = 'tron';
    const BRIDGE_WALLET = 'bridge_wallet';
    const WIRE = 'wire';
    const ACH = 'ach';
    const ACH_PUSH = 'ach_push';
    const ACH_SAME_DAY = 'ach_same_day';
    const SEPA = 'sepa';
    const SWIFT = 'swift';
    const SPEI = 'spei';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ETHEREUM
            self::SOLANA
            self::POLYGON
            self::AVALANCHE_C_CHAIN
            self::BASE
            self::ARBITRUM
            self::OPTIMISM
            self::STELLAR
            self::TRON
            self::BRIDGE_WALLET
            self::WIRE
            self::ACH
            self::ACH_PUSH
            self::ACH_SAME_DAY
            self::SEPA
            self::SWIFT
            self::SPEI
        ];
    }
}
