<?php
/**
 * DestinationCurrency
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevDraftAISDK\Model;
use \DevDraftAISDK\ObjectSerializer;

/**
 * DestinationCurrency Class Doc Comment
 *
 * @category Class
 * @description Currency for sending funds
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DestinationCurrency
{
    /**
     * Possible values of this enum
     */
    const USD = 'usd';
    const EUR = 'eur';
    const MXN = 'mxn';
    const USDC = 'usdc';
    const EURC = 'eurc';
    const DAI = 'dai';
    const PYUSD = 'pyusd';
    const USDT = 'usdt';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USD
            self::EUR
            self::MXN
            self::USDC
            self::EURC
            self::DAI
            self::PYUSD
            self::USDT
        ];
    }
}
