<?php
/**
 * FiatCurrency
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DevDraftAISDK\Model;
use \DevDraftAISDK\ObjectSerializer;

/**
 * FiatCurrency Class Doc Comment
 *
 * @category Class
 * @description The fiat currency to convert FROM. Must match the currency of the source payment rail.
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FiatCurrency
{
    /**
     * Possible values of this enum
     */
    const USD = 'usd';
    const EUR = 'eur';
    const MXN = 'mxn';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USD
            self::EUR
            self::MXN
        ];
    }
}
