<?php
/**
 * CreateDirectBankTransferDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevDraftAISDK;

use PHPUnit\Framework\TestCase;

/**
 * CreateDirectBankTransferDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CreateDirectBankTransferDto
 * @package     DevDraftAISDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateDirectBankTransferDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateDirectBankTransferDto"
     */
    public function testCreateDirectBankTransferDto()
    {
    }

    /**
     * Test attribute "wallet_id"
     */
    public function testPropertyWalletId()
    {
    }

    /**
     * Test attribute "payment_rail"
     */
    public function testPropertyPaymentRail()
    {
    }

    /**
     * Test attribute "destination_currency"
     */
    public function testPropertyDestinationCurrency()
    {
    }

    /**
     * Test attribute "source_currency"
     */
    public function testPropertySourceCurrency()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "wire_message"
     */
    public function testPropertyWireMessage()
    {
    }

    /**
     * Test attribute "sepa_reference"
     */
    public function testPropertySepaReference()
    {
    }

    /**
     * Test attribute "ach_reference"
     */
    public function testPropertyAchReference()
    {
    }
}
