<?php
/**
 * CreatePaymentLinkDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevDraftAISDK;

use PHPUnit\Framework\TestCase;

/**
 * CreatePaymentLinkDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CreatePaymentLinkDto
 * @package     DevDraftAISDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreatePaymentLinkDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreatePaymentLinkDto"
     */
    public function testCreatePaymentLinkDto()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "cover_image"
     */
    public function testPropertyCoverImage()
    {
    }

    /**
     * Test attribute "link_type"
     */
    public function testPropertyLinkType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "payment_for_id"
     */
    public function testPropertyPaymentForId()
    {
    }

    /**
     * Test attribute "recurring_type"
     */
    public function testPropertyRecurringType()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "payment_link_products"
     */
    public function testPropertyPaymentLinkProducts()
    {
    }

    /**
     * Test attribute "is_for_all_product"
     */
    public function testPropertyIsForAllProduct()
    {
    }

    /**
     * Test attribute "allow_quantity_adjustment"
     */
    public function testPropertyAllowQuantityAdjustment()
    {
    }

    /**
     * Test attribute "collect_tax"
     */
    public function testPropertyCollectTax()
    {
    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {
    }

    /**
     * Test attribute "collect_address"
     */
    public function testPropertyCollectAddress()
    {
    }

    /**
     * Test attribute "require_phone_number"
     */
    public function testPropertyRequirePhoneNumber()
    {
    }

    /**
     * Test attribute "limit_payments"
     */
    public function testPropertyLimitPayments()
    {
    }

    /**
     * Test attribute "max_payments"
     */
    public function testPropertyMaxPayments()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "allow_business_tax_id"
     */
    public function testPropertyAllowBusinessTaxId()
    {
    }

    /**
     * Test attribute "allow_mobile_payment"
     */
    public function testPropertyAllowMobilePayment()
    {
    }

    /**
     * Test attribute "confirmation_page"
     */
    public function testPropertyConfirmationPage()
    {
    }

    /**
     * Test attribute "create_invoice_pdf"
     */
    public function testPropertyCreateInvoicePdf()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }
}
