<?php
/**
 * LiquidationAddressResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DevDraftAISDK;

use PHPUnit\Framework\TestCase;

/**
 * LiquidationAddressResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description LiquidationAddressResponseDto
 * @package     DevDraftAISDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LiquidationAddressResponseDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LiquidationAddressResponseDto"
     */
    public function testLiquidationAddressResponseDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "chain"
     */
    public function testPropertyChain()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "external_account_id"
     */
    public function testPropertyExternalAccountId()
    {
    }

    /**
     * Test attribute "prefunded_account_id"
     */
    public function testPropertyPrefundedAccountId()
    {
    }

    /**
     * Test attribute "bridge_wallet_id"
     */
    public function testPropertyBridgeWalletId()
    {
    }

    /**
     * Test attribute "destination_payment_rail"
     */
    public function testPropertyDestinationPaymentRail()
    {
    }

    /**
     * Test attribute "destination_currency"
     */
    public function testPropertyDestinationCurrency()
    {
    }

    /**
     * Test attribute "custom_developer_fee_percent"
     */
    public function testPropertyCustomDeveloperFeePercent()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
