<?php
/**
 * LiquidationAddressesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.65
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DevDraftAISDK;

use DevDraftAISDK\Configuration;
use DevDraftAISDK\ApiException;
use DevDraftAISDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LiquidationAddressesApiTest Class Doc Comment
 *
 * @category Class
 * @package  DevDraftAISDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LiquidationAddressesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for liquidationAddressControllerCreateLiquidationAddress
     *
     * Create a new liquidation address for a customer.
     *
     */
    public function testLiquidationAddressControllerCreateLiquidationAddress()
    {
    }

    /**
     * Test case for liquidationAddressControllerGetLiquidationAddress
     *
     * Get a specific liquidation address.
     *
     */
    public function testLiquidationAddressControllerGetLiquidationAddress()
    {
    }

    /**
     * Test case for liquidationAddressControllerGetLiquidationAddresses
     *
     * Get all liquidation addresses for a customer.
     *
     */
    public function testLiquidationAddressControllerGetLiquidationAddresses()
    {
    }
}
